/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Cuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    Cuenta c;

    public principal() {
        initComponents();
        cmdGuardar.setEnabled(true);
        cmdIngresar.setEnabled(false);
        cmdActualizar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdBorrar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        txtRetirar.setEditable(false);
        txtIngresar.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNumeroCuenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtInteresAnual = new javax.swing.JTextField();
        txtSaldoActual = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIngresar = new javax.swing.JTextField();
        txtRetirar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        cmdBorrar = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        cmdActualizar = new javax.swing.JButton();
        cmdRetirar = new javax.swing.JButton();
        cmdIngresar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel1.setText("Ejercicio 5");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Iniciales"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumeroCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroCuentaKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, 30));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel8.setText("No. de Cuenta");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtInteresAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInteresAnualActionPerformed(evt);
            }
        });
        txtInteresAnual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInteresAnualKeyTyped(evt);
            }
        });
        jPanel2.add(txtInteresAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 100, 30));

        txtSaldoActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoActualKeyTyped(evt);
            }
        });
        jPanel2.add(txtSaldoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 100, 30));

        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyTyped(evt);
            }
        });
        jPanel2.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 100, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel5.setText("Saldo Actual");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel7.setText("Cantidad a retirar");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel6.setText("ID del cliente");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel9.setText("Interés Anual");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel10.setText("Cantidad a ingresar");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresarActionPerformed(evt);
            }
        });
        txtIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIngresarKeyTyped(evt);
            }
        });
        jPanel2.add(txtIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 100, 30));

        txtRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRetirarActionPerformed(evt);
            }
        });
        txtRetirar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRetirarKeyTyped(evt);
            }
        });
        jPanel2.add(txtRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 230, 220));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Resultantes"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 90));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 230, 120));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 130, 40));

        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 40));

        cmdActualizar.setText("Actualizar Saldo");
        cmdActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 40));

        cmdRetirar.setText("Retirar Saldo");
        cmdRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRetirarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 40));

        cmdIngresar.setText("Ingresar Saldo");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 130, 40));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 180, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActualizarActionPerformed
        try {
            double act;
            act = Double.parseDouble(txtInteresAnual.getText());
            c.ActualizarSaldo(act);
            txtResultado.append("\nSu saldo se ha actualizado a: " + c.getSactual() + "\n");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Digite un número valido");
            txtInteresAnual.setEditable(true);
            txtInteresAnual.selectAll();
            txtInteresAnual.requestFocusInWindow();
            
        }
        cmdGuardar.setEnabled(false);
        cmdIngresar.setEnabled(true);
        cmdActualizar.setEnabled(true);
        cmdRetirar.setEnabled(true);
        cmdBorrar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        txtRetirar.setEditable(true);
        txtIngresar.setEditable(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_cmdActualizarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        long numerocuenta, identificacion;
        double saldoactual;

        if (txtNumeroCuenta.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el número de cuenta");
            txtNumeroCuenta.requestFocusInWindow();

        } else if (txtIdentificacion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el número de identificacion");
            txtIdentificacion.requestFocusInWindow();
        } else if (txtSaldoActual.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese su saldo actual");
            txtSaldoActual.requestFocusInWindow();
        } else if (txtInteresAnual.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el interes anual");
            txtInteresAnual.requestFocusInWindow();
        } else {

            numerocuenta = Long.parseLong(txtNumeroCuenta.getText());
            identificacion = Long.parseLong(txtIdentificacion.getText());
            saldoactual = Double.parseDouble(txtSaldoActual.getText());

            c = new Cuenta(numerocuenta, identificacion, saldoactual);
            JOptionPane.showMessageDialog(this, "Guardado exitosamente");
            txtInteresAnual.setEditable(false);
            txtNumeroCuenta.setEditable(false);
            txtIdentificacion.setEditable(false);
            txtSaldoActual.setEditable(false);

            cmdGuardar.setEnabled(false);
            cmdIngresar.setEnabled(false);
            cmdActualizar.setEnabled(false);
            cmdRetirar.setEnabled(false);
            cmdBorrar.setEnabled(true);
            cmdMostrar.setEnabled(true);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        c.mostrar();
        txtResultado.append(c.mostrar() + "\n");
        cmdGuardar.setEnabled(false);
        cmdIngresar.setEnabled(false);
        cmdActualizar.setEnabled(true);
        cmdRetirar.setEnabled(false);
        cmdBorrar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed
        double ing;

        if (txtIngresar.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor digite la cantidad a ingresar");
            txtIngresar.requestFocusInWindow();

        } else {

            ing = Double.parseDouble(txtIngresar.getText());
            c.Ingresar(ing);
            txtIngresar.setText("");
            txtRetirar.setText("");
            txtResultado.append("Saldo actual: " + c.getSactual() + "\n");

        }
        cmdGuardar.setEnabled(false);
        cmdIngresar.setEnabled(true);
        cmdActualizar.setEnabled(false);
        cmdRetirar.setEnabled(true);
        cmdBorrar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdIngresarActionPerformed

    private void cmdRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRetirarActionPerformed
        double ret, sa;

        if (txtRetirar.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "por favor digite la cantidad a retirar ");
            txtRetirar.requestFocusInWindow();
        } else {
            ret = Double.parseDouble(txtRetirar.getText());
            sa = c.getSactual();
            if (sa < ret) {
                JOptionPane.showMessageDialog(this, "No hay suficiente saldo en su cuenta para el retiro");
                txtRetirar.setText("");
            } else {
                c.Retirar(ret);
                txtRetirar.setText("");
                txtIngresar.setText("");
                txtResultado.append("Saldo actual: " + c.getSactual() + "\n");
            }
        }
        cmdGuardar.setEnabled(false);
        cmdIngresar.setEnabled(true);
        cmdActualizar.setEnabled(false);
        cmdRetirar.setEnabled(true);
        cmdBorrar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        //}
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdRetirarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        c = null;
        txtResultado.setText("");
        txtInteresAnual.setText("");
        txtNumeroCuenta.setText("");
        txtIdentificacion.setText("");
        txtSaldoActual.setText("");

        cmdGuardar.setEnabled(true);
        cmdIngresar.setEnabled(false);
        cmdActualizar.setEnabled(false);
        cmdRetirar.setEnabled(false);
        cmdBorrar.setEnabled(true);
        cmdMostrar.setEnabled(false);

        txtNumeroCuenta.setEditable(true);
        txtIdentificacion.setEditable(true);
        txtSaldoActual.setEditable(true);
        txtInteresAnual.setEditable(true);
        txtRetirar.setEditable(false);
        txtIngresar.setEditable(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtNumeroCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroCuentaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCuentaKeyTyped

    private void txtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionKeyTyped

    private void txtSaldoActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoActualKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActualKeyTyped

    private void txtInteresAnualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInteresAnualKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_txtInteresAnualKeyTyped

    private void txtInteresAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInteresAnualActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtInteresAnualActionPerformed

    private void txtRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetirarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRetirarActionPerformed

    private void txtRetirarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetirarKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRetirarKeyTyped

    private void txtIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresarActionPerformed

    private void txtIngresarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresarKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdActualizar;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtIngresar;
    private javax.swing.JTextField txtInteresAnual;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtRetirar;
    private javax.swing.JTextField txtSaldoActual;
    // End of variables declaration//GEN-END:variables
}
